baseURL = "https://khaleel737.github.io/"
languageCode = "en-us"
title = "Khaleel Musleh"
theme = "yinyang"
enableRobotsTXT = true
pygmentsUseClasses = true

[params.author]
  email = "maxhalford25@gmail.com"
  name = "Khaleel Musleh"

[params]
  headTitle = "Khaleel Musleh ツ"
  mainSections = ["blog"]
  favicon = "/img/favicon.ico"
  images = ["/img/belle-ile.jpg"]
  description = "Khaleel Musleh's blog ツ"

[markup.goldmark.renderer]
  unsafe = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[robots]
  llmsTXT = true
